const name = "Weis"

module.exports = {
    apps: 
    [ 
        {
        name: `${name} - Shield I`,
        script: 'main.js',
        watch: true,
        exec_mode: "cluster",
        max_memory_restart: "2G",
        cwd: "./Shield_I"
      }, 
        {
        name: `${name} - Shield II`,
        script: 'main.js',
        watch: true,
        exec_mode: "cluster",
        max_memory_restart: "2G",
        cwd: "./Shield_II"
      }, 
         ]
  };
  /*
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
*/