module.exports = {
    ShieldI:"TOKEN1",
    Shield2:"TOKEN2",
    guildID:"GUİLDID",
    Mongoose:"MONGODB",
    Owner:["OWNERID"],
    Ses:"BOTSES",
    Durum:["DURUMÇOĞALTILABİLİR"],
    Prefixs:["."]
}
/*
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
https://discord.gg/gjjHmhTFhY
*/
